[package]
name = "jimtel"
version = "0.1.0"
authors = ["youxkei <youxkei@gmail.com>"]
license = "CC0 1.0"
edition = "2018"

#[lib]
#crate-type = ["cdylib"]

[dependencies]

[workspace]
members = [
  "loudness_limiter",
]
