[package]
name = "jimtel"
version = "0.5.0"
authors = ["youxkei <youxkei@gmail.com>"]
license = "CC0 1.0"
edition = "2018"

[dependencies]
vst = "0.2.1"
raw-window-handle = "0.3.3"

[workspace]
members = [
  "params_derive",
  "loudness_limiter",
  "loudness_ceiling",
]
