[package]
name = "jimtel"
version = "0.1.0"
authors = ["youxkei <youxkei@gmail.com>"]
license = "CC0 1.0"
edition = "2018"

[dependencies]
vst = "0.2.1"

[workspace]
members = [
  "params_derive",
  "loudness_limiter",
]
