[package]
name = "loudness_limiter"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
vst = "0.2.1"
itertools = "0.10.0"
raw-window-handle = "0.3.3"
rmp-serde = "0.15.4"
jimtel = { path = ".." }
params_derive = { path = "../params_derive" }
