
{
    name: "Release",

    on: {
        push: {
            tags: ["v*.*.*"],
        },
    },

    env: {
        CARGO_TERM_COLOR: "always",
    },

    jobs: {
        build: {
            strategy: {
                matrix: {
                    os: ["ubuntu-latest", "windows-latest", "macos-latest"],
                    rust: ["nightly"],
                },
            },

            runs-on: "${{ matrix.os }}",

            steps: [
                {
                    name: "Setup Rust",
                    uses: "hecrj/setup-rust-action@v1",
                    with: {
                        rust-version: "${{ matrix.rust }}",
                    },
                },
                {
                    name: "Checkout",
                    uses: "actions/checkout@v2",
                },
                {
                    name: "Install Dependencies",
                    if: "matrix.os == 'ubuntu-latest'",
                    run: "sudo apt update && sudo apt install -qq libgl-dev libxcursor-dev libx11-xcb-dev libxcb-icccm4-dev libxcb-dri2-0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev",
                },
                {
                    name: "Build for Linux",
                    if: "matrix.os == 'ubuntu-latest'",
                    run: "make jimtel_linux.tar.gz",
                },
                {
                    name: "Build for Windows",
                    if: "matrix.os == 'windows-latest'",
                    run: "make jimtel_windows.zip",
                },
                {
                    name: "Build for macOS",
                    if: "matrix.os == 'macOS-latest'",
                    run: "make jimtel_macos.zip",
                },
                {
                    name: "Release",
                    uses: "softprops/action-gh-release@v1",
                    with: {
                        files: "jimtel_*",
                    },
                    env: {
                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                    }
                }
            ],
        },
    },
}
